// Client Hub — Drive-backed documents and a unified action center.
let _hubData = { documents:[], actions:[], folderUrl:"" };
let _hubTab = "overview";

const HUB_TYPES = {
  document_request:["Upload Request","bi-cloud-arrow-up-fill"], task:["Between-Session Task","bi-check2-square"],
  form:["Form / Signature","bi-ui-checks-grid"], resource:["Resource","bi-book-fill"], insurance:["Insurance Item","bi-shield-check"],
  care_team:["Care-Team Update","bi-people-fill"], support_plan:["Support Plan","bi-life-preserver"],
  communication:["Communication Preference","bi-chat-heart-fill"], agenda:["Session Agenda","bi-card-checklist"]
};

async function initClientHubSection(root) {
  root.innerHTML = `<div class="card"><div class="portal-loading-status"><div class="pls-spinner"></div><span>Loading Client Hub…</span></div></div>`;
  try { _hubData = await apiCall("getClientHub", {}); hubRender(root); }
  catch(e) { root.innerHTML=`<div class="card"><div class="alert alert-error"><i class="bi bi-exclamation-triangle-fill"></i><span>${escapeHtml(e.message)}</span></div></div>`; }
}

function hubRender(root) {
  const provider=getRole()==="provider", open=_hubData.actions.filter(a=>a.status!=="completed"), required=open.filter(a=>a.requiresAction);
  const docs=_hubData.documents.filter(d=>provider||d.visible), pendingDocs=docs.filter(d=>(d.requireAck||d.requireSignature)&&!d.acknowledgedAt);
  root.innerHTML=`
    <div class="hub-hero"><div><span class="hub-eyebrow">Connected care workspace</span><h1><i class="bi bi-grid-1x2-fill"></i> Client Hub</h1><p>Documents, requests, resources, forms, plans, and next steps in one place.</p></div>${provider&&_hubData.folderUrl?`<a class="secondary button" href="${escapeAttr(_hubData.folderUrl)}" target="_blank" rel="noopener noreferrer"><i class="bi bi-google"></i> Open Drive Folder</a>`:""}</div>
    <div class="hub-stats"><button onclick="hubSetTab('actions')"><strong>${required.length}</strong><span>Action required</span></button><button onclick="hubSetTab('documents')"><strong>${docs.length}</strong><span>Shared documents</span></button><button onclick="hubSetTab('documents')"><strong>${pendingDocs.length}</strong><span>Need acknowledgment</span></button><button onclick="hubSetTab('actions')"><strong>${open.length}</strong><span>Open items</span></button></div>
    <div class="hub-tabs"><button class="${_hubTab==='overview'?'active':''}" onclick="hubSetTab('overview')"><i class="bi bi-stars"></i> Overview</button><button class="${_hubTab==='documents'?'active':''}" onclick="hubSetTab('documents')"><i class="bi bi-folder2-open"></i> Documents</button><button class="${_hubTab==='actions'?'active':''}" onclick="hubSetTab('actions')"><i class="bi bi-list-check"></i> Action Center</button>${provider?`<button class="${_hubTab==='create'?'active':''}" onclick="hubSetTab('create')"><i class="bi bi-plus-circle-fill"></i> Assign</button>`:""}</div>
    <div id="hub-panel">${hubPanelHtml(provider)}</div>`;
}

function hubSetTab(tab){_hubTab=tab;const root=document.getElementById("section-client-hub");if(root)hubRender(root);}
function hubPanelHtml(provider){if(_hubTab==="documents")return hubDocumentsHtml(provider);if(_hubTab==="actions")return hubActionsHtml(provider);if(_hubTab==="create"&&provider)return hubCreateHtml();return hubOverviewHtml(provider);}

function hubOverviewHtml(provider){
  const actions=_hubData.actions.filter(a=>a.status!=="completed").slice(0,6), docs=_hubData.documents.filter(d=>provider||d.visible).slice(0,6);
  return `<div class="hub-two-col"><section class="card"><div class="hub-section-head"><h2><i class="bi bi-lightning-charge-fill"></i> Next actions</h2><button class="secondary" onclick="hubSetTab('actions')">View all</button></div>${actions.length?actions.map(a=>hubActionCard(a,provider)).join(""):`<div class="hub-empty"><i class="bi bi-check-circle-fill"></i><strong>All caught up</strong><span>No open action items.</span></div>`}</section><section class="card"><div class="hub-section-head"><h2><i class="bi bi-folder-fill"></i> Recent documents</h2><button class="secondary" onclick="hubSetTab('documents')">View all</button></div><div class="hub-doc-grid">${docs.length?docs.map(d=>hubDocumentCard(d,provider)).join(""):`<div class="hub-empty"><i class="bi bi-folder2-open"></i><strong>No documents yet</strong></div>`}</div></section></div>`;
}

function hubDocumentsHtml(provider){
  const docs=_hubData.documents;
  if(!docs.length)return `<div class="card hub-empty"><i class="bi bi-folder2-open"></i><strong>No files found</strong><span>${provider?'Add files to the client’s Drive folder, then refresh this page.':'Your provider has not shared documents yet.'}</span></div>`;
  if(!provider)return `<div class="hub-doc-grid">${docs.map(d=>hubDocumentCard(d,false)).join("")}</div>`;
  return `<div class="card"><div class="hub-section-head"><div><h2><i class="bi bi-folder-check"></i> Repository visibility</h2><p>Choose exactly which Drive files appear in the client portal.</p></div><button class="secondary" onclick="initClientHubSection(document.getElementById('section-client-hub'))"><i class="bi bi-arrow-clockwise"></i> Sync Drive</button></div><div class="hub-provider-docs">${docs.map(hubDocumentSettings).join("")}</div></div>`;
}

function hubDocumentCard(d,provider){
  const icon=d.mimeType?.includes("pdf")?"bi-file-earmark-pdf-fill":d.mimeType?.includes("document")?"bi-file-earmark-text-fill":"bi-file-earmark-fill";
  return `<article class="hub-doc-card"><div class="hub-doc-icon"><i class="bi ${icon}"></i></div><div class="hub-doc-main"><div class="hub-doc-badges"><span>${escapeHtml(d.category||"Documents")}</span>${d.updatedSinceShared?`<span class="updated">Updated</span>`:""}${d.requireSignature?`<span class="required">Signature</span>`:d.requireAck?`<span class="required">Acknowledge</span>`:""}</div><h3>${escapeHtml(d.displayTitle||d.name)}</h3>${d.summary?`<p>${escapeHtml(d.summary)}</p>`:""}<small>${escapeHtml(d.bundle?d.bundle+" · ":"")}${escapeHtml(d.modifiedAt?new Date(d.modifiedAt).toLocaleDateString():"")}</small><div class="hub-doc-actions">${provider?`<a href="${escapeAttr(d.url)}" target="_blank" rel="noopener noreferrer" class="button secondary"><i class="bi bi-google"></i> Drive</a>`:`<button class="secondary" onclick="hubDownload('${escapeAttr(d.fileId)}')"><i class="bi bi-eye-fill"></i> ${d.allowDownload?'Open / Download':'View'}</button>${(d.requireAck||d.requireSignature)&&!d.acknowledgedAt?`<button onclick="hubAcknowledge('${escapeAttr(d.fileId)}')"><i class="bi bi-check-circle-fill"></i> ${d.requireSignature?'Confirm signed':'Acknowledge'}</button>`:d.acknowledgedAt?`<span class="hub-complete"><i class="bi bi-check-circle-fill"></i> Completed</span>`:""}`}</div></div></article>`;
}

function hubDocumentSettings(d){return `<article class="hub-doc-settings" id="hub-doc-${escapeAttr(d.fileId)}"><div class="hub-doc-file"><i class="bi bi-file-earmark-fill"></i><div><strong>${escapeHtml(d.name)}</strong><small>${escapeHtml(d.path||"Documents")}${d.updatedSinceShared?' · Updated since shared':''}</small></div><label class="hub-toggle"><input data-k="visible" type="checkbox" ${d.visible?'checked':''}><span>Show</span></label></div><div class="hub-doc-fields"><input data-k="displayTitle" value="${escapeAttr(d.displayTitle||d.name)}" placeholder="Portal title"><input data-k="category" value="${escapeAttr(d.category||'Documents')}" placeholder="Category"><select data-k="audience"><option value="all" ${d.audience==='all'?'selected':''}>Client + linked adults</option><option value="client" ${d.audience==='client'?'selected':''}>Client only</option><option value="adults" ${d.audience==='adults'?'selected':''}>Linked adults only</option></select><input data-k="bundle" value="${escapeAttr(d.bundle||'')}" placeholder="Bundle / packet"><input data-k="dueDate" type="date" value="${escapeAttr(d.dueDate||'')}"><textarea data-k="summary" rows="2" placeholder="Client-friendly description or instructions">${escapeHtml(d.summary||'')}</textarea></div><div class="hub-doc-options"><label><input data-k="allowDownload" type="checkbox" ${d.allowDownload?'checked':''}> Download</label><label><input data-k="requireAck" type="checkbox" ${d.requireAck?'checked':''}> Acknowledgment</label><label><input data-k="requireSignature" type="checkbox" ${d.requireSignature?'checked':''}> Signature</label><label><input data-k="archived" type="checkbox" ${d.archived?'checked':''}> Archive</label><button onclick="hubSaveDocument('${escapeAttr(d.fileId)}')"><i class="bi bi-floppy-fill"></i> Save</button></div><div class="hub-row-status"></div></article>`;}

function hubActionsHtml(provider){const actions=_hubData.actions;return `<div class="card"><div class="hub-section-head"><div><h2><i class="bi bi-list-check"></i> Action Center</h2><p>Tasks, uploads, forms, resources, plans, and preparation items.</p></div>${provider?`<button onclick="hubSetTab('create')"><i class="bi bi-plus-lg"></i> Assign item</button>`:""}</div><div class="hub-action-list">${actions.length?actions.map(a=>hubActionCard(a,provider)).join(""):`<div class="hub-empty"><i class="bi bi-check-circle-fill"></i><strong>No action items</strong></div>`}</div></div>`;}

function hubActionCard(a,provider){const meta=HUB_TYPES[a.type]||["Action Item","bi-check2-square"],done=a.status==="completed";return `<article class="hub-action ${done?'done':''}"><div class="hub-action-icon"><i class="bi ${meta[1]}"></i></div><div class="hub-action-main"><div class="hub-action-meta"><span>${escapeHtml(meta[0])}</span>${a.dueDate?`<span class="${!done&&a.dueDate<new Date().toISOString().slice(0,10)?'overdue':''}"><i class="bi bi-calendar3"></i> ${escapeHtml(a.dueDate)}</span>`:""}<span class="status">${escapeHtml(a.status.replace('_',' '))}</span></div><h3>${escapeHtml(a.title)}</h3>${a.details?`<p>${escapeHtml(a.details)}</p>`:""}${a.response?`<div class="hub-response"><strong>Response:</strong> ${escapeHtml(a.response)}</div>`:""}<div class="hub-action-buttons">${a.url?`<a class="button secondary" href="${escapeAttr(a.url)}" target="_blank" rel="noopener noreferrer"><i class="bi bi-box-arrow-up-right"></i> Open</a>`:""}${!provider&&!done&&a.type==='document_request'?`<label class="button secondary"><i class="bi bi-cloud-arrow-up-fill"></i> Upload<input type="file" hidden onchange="hubUpload(this,'${escapeAttr(a.actionId)}')"></label>`:""}${!done?`<button onclick="hubUpdateAction('${escapeAttr(a.actionId)}','completed')"><i class="bi bi-check-lg"></i> ${provider?'Mark complete':'Complete'}</button>`:`<span class="hub-complete"><i class="bi bi-check-circle-fill"></i> Completed</span>`}</div></div></article>`;}

function hubCreateHtml(){return `<div class="card hub-create"><h2><i class="bi bi-plus-circle-fill"></i> Assign to Action Center</h2><div class="hub-create-grid"><label>Type<select id="hub-new-type">${Object.entries(HUB_TYPES).map(([v,m])=>`<option value="${v}">${m[0]}</option>`).join('')}</select></label><label>Audience<select id="hub-new-audience"><option value="all">Client + linked adults</option><option value="client">Client only</option><option value="adults">Linked adults only</option></select></label><label class="wide">Title<input id="hub-new-title" placeholder="What needs attention?"></label><label class="wide">Instructions<textarea id="hub-new-details" rows="4"></textarea></label><label>Due date<input id="hub-new-due" type="date"></label><label>Related link<input id="hub-new-url" type="url" placeholder="https://..."></label></div><button onclick="hubCreateAction()"><i class="bi bi-send-fill"></i> Add to Action Center</button><div id="hub-create-status"></div></div>`;}

async function hubSaveDocument(fileId){const row=document.getElementById('hub-doc-'+CSS.escape(fileId)),status=row?.querySelector('.hub-row-status');if(!row)return;const value=k=>row.querySelector(`[data-k="${k}"]`),payload={fileId,displayTitle:value('displayTitle').value,category:value('category').value,audience:value('audience').value,bundle:value('bundle').value,dueDate:value('dueDate').value,summary:value('summary').value,visible:value('visible').checked,allowDownload:value('allowDownload').checked,requireAck:value('requireAck').checked,requireSignature:value('requireSignature').checked,archived:value('archived').checked};if(status)status.textContent='Saving…';try{await apiCall('saveClientDocumentSettings',payload);if(status)status.innerHTML='<span class="hub-complete"><i class="bi bi-check-circle-fill"></i> Saved</span>';}catch(e){if(status)status.textContent=e.message;}}
async function hubAcknowledge(fileId){try{await apiCall('acknowledgeClientDocument',{fileId});await initClientHubSection(document.getElementById('section-client-hub'));}catch(e){showToast(e.message,'error');}}
async function hubDownload(fileId){showToast('Preparing document…','info');try{const r=await apiCall('downloadClientDocument',{fileId}),a=document.createElement('a');a.href=`data:${r.mimeType};base64,${r.base64}`;a.download=r.fileName||'document';a.target='_blank';document.body.appendChild(a);a.click();a.remove();}catch(e){showToast(e.message,'error');}}
async function hubUpload(input,actionId){const file=input.files?.[0];if(!file)return;if(file.size>8*1024*1024){showToast('Files must be 8 MB or smaller.','error');return;}const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=reject;reader.readAsDataURL(file);});try{await apiCall('uploadClientDocument',{fileName:file.name,mimeType:file.type,base64,actionId});showToast('Document uploaded.','success');await initClientHubSection(document.getElementById('section-client-hub'));}catch(e){showToast(e.message,'error');}}
async function hubUpdateAction(actionId,status){try{await apiCall('updateClientAction',{actionId,status});await initClientHubSection(document.getElementById('section-client-hub'));}catch(e){showToast(e.message,'error');}}
async function hubCreateAction(){const payload={type:document.getElementById('hub-new-type').value,audience:document.getElementById('hub-new-audience').value,title:document.getElementById('hub-new-title').value,details:document.getElementById('hub-new-details').value,dueDate:document.getElementById('hub-new-due').value,url:document.getElementById('hub-new-url').value,requiresAction:true};setStatus('hub-create-status','Creating…','loading');try{await apiCall('createClientAction',payload);_hubTab='actions';await initClientHubSection(document.getElementById('section-client-hub'));}catch(e){setStatus('hub-create-status',e.message,'error');}}
