// Unified provider Program Studio. Loaded after program-admin.js and intentionally
// replaces initProgramAdminSection while retaining the existing assignment APIs.

let studioPrograms = [];
let studioGoals = [];
let studioCurrent = null;
let studioStep = 1;
let studioAiOutcomes = [];

const STUDIO_AUDIENCE_COLORS = {
  parent:"#7c3aed", child:"#2563eb", teen:"#d97706", adult:"#059669", family:"#e11d48", all:"#64748b"
};
function studioAudienceColor(audience){return STUDIO_AUDIENCE_COLORS[String(audience||"all").toLowerCase()]||STUDIO_AUDIENCE_COLORS.all;}

function studioBlankProgram() {
  return {
    programId:"", name:"", description:"", audience:"parent", durationWeeks:8,
    sessionsPerWeek:1, color:"#6366f1", icon:"bi-signpost-split-fill", outcomes:[],
    weeks:[{ week:1, phase:"Foundation", milestone:"", sessions:[studioBlankSession(1)] }]
  };
}

function studioBlankSession(n) {
  return { title:"Session " + n, description:"", focus:"", homework:"", type:"parent+child", activities:[] };
}

async function initProgramAdminSection(root) {
  root.innerHTML = `<div class="studio-loading"><div class="brand-motion"><span></span><span></span><span></span></div><strong>Opening Program Studio…</strong></div>`;
  try {
    const [library, progress, goals] = await Promise.all([
      apiCall("getProgramStudioLibrary", {}),
      apiCall("getClientProgramProgress", {}).catch(() => ({ assignment:null, steps:[] })),
      apiCall("getPlan", {}).catch(() => ({ goals:[] }))
    ]);
    studioPrograms = library.programs || [];
    studioGoals = goals.goals || [];
    studioRenderShell(root, progress);
  } catch (e) {
    root.innerHTML = `<div class="card"><div class="alert alert-error"><i class="bi bi-exclamation-triangle-fill"></i><span>${escapeHtml(e.message)}</span></div></div>`;
  }
}

function studioRenderShell(root, progress) {
  const current = progress.assignment;
  const steps = progress.steps || [];
  const completed = steps.filter(s => s.status === "completed").length;
  const pct = steps.length ? Math.round(completed / steps.length * 100) : 0;
  root.innerHTML = `
    <div class="studio-hero card">
      <div class="studio-orb one"></div><div class="studio-orb two"></div>
      <div class="studio-hero-copy"><div class="studio-kicker"><span></span> PROGRAM DESIGN WORKSPACE</div>
        <h1><i class="bi bi-stars"></i> Program Studio</h1>
        <p>Design, personalize, preview, and assign clinical journeys from one workspace.</p>
      </div>
      <button class="studio-primary" onclick="studioStartNew()"><i class="bi bi-plus-lg"></i> Create Program</button>
    </div>
    ${current ? `<div class="studio-current card">
      <div class="studio-current-icon"><i class="bi bi-play-circle-fill"></i></div>
      <div style="flex:1;min-width:220px;"><div class="studio-label">CURRENT CLIENT PROGRAM</div><h2>${escapeHtml(current.programName)}</h2>
        <div class="studio-progress"><span style="width:${pct}%"></span></div><small>${completed} of ${steps.length} activities complete · started ${escapeHtml(current.startDate)}</small>
      </div><button class="secondary" onclick="studioScrollLibrary()"><i class="bi bi-arrow-repeat"></i> Change program</button>
    </div>` : `<div class="studio-empty-current"><i class="bi bi-lightning-charge-fill"></i><span>No active digital program for this client.</span><button onclick="studioStartNew()">Build one</button></div>`}
    <div class="studio-tabs"><button id="studio-tab-library" class="active" onclick="studioShowTab('library')"><i class="bi bi-grid-fill"></i> Library</button><button id="studio-tab-builder" onclick="studioShowTab('builder')"><i class="bi bi-tools"></i> Builder</button></div>
    <div id="studio-library"></div><div id="studio-builder" style="display:none;"></div>
    <style>${studioCss()}</style>`;
  studioRenderLibrary();
}

function studioCss() { return `
  .studio-loading{min-height:360px;display:grid;place-content:center;text-align:center;gap:16px;color:var(--muted)}
  .studio-hero{position:relative;overflow:hidden;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px;background:linear-gradient(130deg,color-mix(in srgb,var(--primary) 13%,var(--card,#fff)),var(--card,#fff) 55%,rgba(6,182,212,.12));box-shadow:0 18px 42px rgba(49,133,252,.1)}
  .studio-hero-copy{position:relative;z-index:2}.studio-hero h1{margin:5px 0 6px;font-size:28px}.studio-hero p{margin:0;color:var(--muted)}
  .studio-kicker,.studio-label{font-size:10px;font-weight:900;letter-spacing:.13em;color:var(--primary)}.studio-kicker span{display:inline-block;width:7px;height:7px;border-radius:50%;background:#22c55e;margin-right:7px;box-shadow:0 0 0 5px rgba(34,197,94,.13)}
  .studio-orb{position:absolute;border-radius:50%;filter:blur(2px);opacity:.65;animation:studioFloat 7s ease-in-out infinite}.studio-orb.one{width:230px;height:230px;right:-80px;top:-120px;background:radial-gradient(circle,#67e8f9,transparent 68%)}.studio-orb.two{width:160px;height:160px;right:24%;bottom:-130px;background:radial-gradient(circle,#c4b5fd,transparent 70%);animation-delay:-3s}
  .studio-primary{position:relative;z-index:2;background:linear-gradient(135deg,#4f46e5,#7c3aed);box-shadow:0 10px 24px rgba(79,70,229,.25)}
  .studio-current{display:flex;align-items:center;gap:16px;border-left:4px solid #10b981}.studio-current h2{margin:2px 0 9px;font-size:18px}.studio-current-icon{width:46px;height:46px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,#059669,#34d399);color:#fff;font-size:21px}.studio-progress{height:8px;background:var(--border);border-radius:99px;overflow:hidden;max-width:520px}.studio-progress span{display:block;height:100%;background:linear-gradient(90deg,#10b981,#22d3ee);border-radius:inherit;transition:width .7s ease}.studio-current small{display:block;margin-top:6px;color:var(--muted)}
  .studio-empty-current{display:flex;align-items:center;gap:10px;padding:12px 16px;border:1px dashed var(--border);border-radius:12px;margin-bottom:14px;color:var(--muted)}.studio-empty-current button{margin-left:auto}
  .studio-tabs{display:flex;gap:8px;margin:4px 0 14px}.studio-tabs button{background:transparent;color:var(--muted);border-color:transparent;box-shadow:none}.studio-tabs button.active{color:var(--primary);background:color-mix(in srgb,var(--primary) 10%,transparent);border-color:color-mix(in srgb,var(--primary) 25%,transparent)}
  .studio-toolbar{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:14px}.studio-search{position:relative;flex:1;max-width:360px}.studio-search i{position:absolute;left:12px;top:11px;color:var(--muted)}.studio-search input{width:100%;padding-left:34px}
  .studio-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:14px}.studio-card{position:relative;overflow:hidden;border:1.5px solid var(--border);border-radius:16px;padding:18px;background:var(--card,#fff);transition:.2s transform,.2s box-shadow,.2s border-color}.studio-card:hover{transform:translateY(-4px);box-shadow:0 16px 34px rgba(15,23,42,.1);border-color:var(--audience-color)}.studio-card::before{content:"";position:absolute;inset:0 0 auto;height:6px;background:var(--audience-color)}.studio-card-icon{width:43px;height:43px;border-radius:13px;display:grid;place-items:center;background:color-mix(in srgb,var(--studio-color) 13%,transparent);color:var(--studio-color);font-size:19px}.studio-card h3{margin:12px 0 5px}.studio-meta{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.studio-chip{font-size:10px;font-weight:800;padding:3px 7px;border-radius:99px;background:var(--surface);color:var(--muted)}.studio-audience-chip{background:color-mix(in srgb,var(--audience-color) 13%,transparent);color:var(--audience-color);border:1px solid color-mix(in srgb,var(--audience-color) 28%,transparent)}.studio-audience-legend{display:flex;gap:7px;flex-wrap:wrap;margin:-3px 0 14px}.studio-audience-legend span{display:inline-flex;align-items:center;gap:5px;font-size:10px;font-weight:800;color:var(--muted)}.studio-audience-legend i{width:9px;height:9px;border-radius:50%;background:var(--audience-color)}.studio-card-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:13px}.studio-card-actions button{font-size:11px;padding:6px 9px}
  .studio-wizard{display:grid;grid-template-columns:220px 1fr;gap:16px}.studio-steps{padding:12px}.studio-step-nav{display:flex;width:100%;text-align:left;gap:10px;align-items:center;background:transparent!important;color:var(--muted)!important;border:0!important;box-shadow:none!important}.studio-step-nav b{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:var(--surface)}.studio-step-nav.active{color:var(--primary)!important}.studio-step-nav.active b{background:var(--primary);color:#fff}.studio-builder-card{min-width:0}.studio-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.studio-form-grid .wide{grid-column:1/-1}.studio-outcome{display:flex;gap:8px;margin-bottom:8px}.studio-outcome input{flex:1}.studio-outcome-drop{border:1.5px dashed #93c5fd;border-radius:13px;padding:12px;background:#eff6ff}.studio-ai-outcomes{display:grid;gap:8px;margin-top:10px}.studio-ai-outcome{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:center;padding:10px;border:1px solid #c7d2fe;border-radius:11px;background:var(--card,#fff);cursor:grab}.studio-ai-outcome span{font-size:12px}.studio-ai-outcome button{font-size:10px;padding:5px 7px}
  .studio-week{border:1.5px solid var(--border);border-radius:15px;margin-bottom:12px;overflow:hidden;background:var(--card,#fff)}.studio-week-head{display:flex;align-items:center;gap:8px;padding:12px;background:linear-gradient(90deg,color-mix(in srgb,var(--primary) 8%,transparent),transparent)}.studio-week-head input{font-weight:700}.studio-session{margin:10px;border:1px solid var(--border);border-radius:12px;padding:13px;background:var(--surface)}.studio-session-top{display:flex;gap:8px;align-items:center}.studio-session-top input{flex:1;font-weight:700}.studio-mini-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.studio-session textarea{width:100%;margin-top:8px;resize:vertical}.studio-icon-btn{padding:6px 8px!important;font-size:12px!important}.studio-builder-actions{position:sticky;bottom:8px;display:flex;justify-content:space-between;gap:10px;padding:12px;margin-top:14px;border:1px solid var(--border);border-radius:13px;background:color-mix(in srgb,var(--card,#fff) 92%,transparent);backdrop-filter:blur(12px);box-shadow:0 10px 30px rgba(15,23,42,.1)}
  .studio-preview-banner{padding:22px;border-radius:16px;color:#fff;background:linear-gradient(135deg,color-mix(in srgb,var(--studio-color) 72%,#1e3a8a),#2563eb 58%,#4f46e5);box-shadow:0 15px 30px rgba(37,99,235,.22)}.studio-preview-week{display:grid;grid-template-columns:45px 1fr;gap:12px;margin-top:14px}.studio-preview-num{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#eff6ff,#e0e7ff);color:#1d4ed8;border:1px solid #bfdbfe;font-weight:900}
  @keyframes studioFloat{50%{transform:translateY(12px) scale(1.05)}}@media(max-width:760px){.studio-wizard{grid-template-columns:1fr}.studio-steps{display:flex;overflow:auto}.studio-form-grid,.studio-mini-grid{grid-template-columns:1fr}.studio-hero{align-items:flex-start;flex-direction:column}}
`; }

function studioShowTab(tab) {
  document.getElementById("studio-library").style.display = tab === "library" ? "block" : "none";
  document.getElementById("studio-builder").style.display = tab === "builder" ? "block" : "none";
  document.getElementById("studio-tab-library").classList.toggle("active", tab === "library");
  document.getElementById("studio-tab-builder").classList.toggle("active", tab === "builder");
}

function studioScrollLibrary(){ studioShowTab("library");document.getElementById("studio-library")?.scrollIntoView({behavior:"smooth"}); }

function studioRenderLibrary() {
  const el = document.getElementById("studio-library"); if (!el) return;
  const audiences=["parent","child","teen","adult","family"].map(a=>`<span style="--audience-color:${studioAudienceColor(a)}"><i></i>${a}</span>`).join("");
  el.innerHTML = `<div class="studio-toolbar"><div class="studio-search"><i class="bi bi-search"></i><input id="studio-search" oninput="studioFilterLibrary()" placeholder="Search programs, audience, outcomes…"></div><div style="display:flex;gap:8px"><select id="studio-audience-filter" onchange="studioFilterLibrary()"><option value="all">All audiences</option><option>parent</option><option>child</option><option>teen</option><option>adult</option><option>family</option></select><button class="secondary" onclick="studioStartNew()"><i class="bi bi-plus-lg"></i> New</button></div></div><div class="studio-audience-legend" aria-label="Audience color key">${audiences}</div><div id="studio-grid" class="studio-grid">${studioPrograms.map(studioProgramCard).join("") || `<div class="card">No programs yet. Create your first reusable template.</div>`}</div>`;
}

function studioProgramCard(p) {
  const search = [p.name,p.description,p.audience,(p.outcomes||[]).join(" ")].join(" ").toLowerCase();
  const audience=p.audience||"all", audienceColor=studioAudienceColor(audience);
  return `<article class="studio-card" data-search="${escapeAttr(search)}" data-audience="${escapeAttr(audience)}" style="--studio-color:${escapeAttr(p.color||"#64748b")};--audience-color:${audienceColor}"><div class="studio-card-icon"><i class="bi ${escapeAttr(p.icon||"bi-collection-play-fill")}"></i></div><h3>${escapeHtml(p.name)}</h3><p style="font-size:12px;color:var(--muted);min-height:36px">${escapeHtml(p.description||"No description yet.")}</p><div class="studio-meta"><span class="studio-chip studio-audience-chip">${escapeHtml(audience)}</span>${p.durationWeeks?`<span class="studio-chip">${p.durationWeeks} weeks</span>`:""}<span class="studio-chip">${p.totalSessions||0} sessions</span>${p.activeClients?`<span class="studio-chip">${p.activeClients} active</span>`:""}<span class="studio-chip">${escapeHtml(p.status||"draft")}${p.version?" · v"+p.version:""}</span></div><div class="studio-card-actions"><button onclick="studioPreview('${escapeAttr(p.programId)}')"><i class="bi bi-eye-fill"></i> Preview</button>${p.status!=="legacy"?`<button class="secondary" onclick="studioEdit('${escapeAttr(p.programId)}')"><i class="bi bi-pencil-fill"></i> Edit</button><button class="secondary" onclick="studioDuplicate('${escapeAttr(p.programId)}')" title="Duplicate"><i class="bi bi-copy"></i></button><button class="secondary" onclick="studioArchive('${escapeAttr(p.programId)}')" title="Archive"><i class="bi bi-archive-fill"></i></button>`:""}<button class="secondary" onclick="studioAssignExisting('${escapeAttr(p.programId)}')"><i class="bi bi-send-fill"></i> Assign</button></div></article>`;
}

function studioFilterLibrary(){const q=(document.getElementById("studio-search")?.value||"").toLowerCase();const a=document.getElementById("studio-audience-filter")?.value||"all";document.querySelectorAll(".studio-card").forEach(c=>c.style.display=(!q||c.dataset.search.includes(q))&&(a==="all"||c.dataset.audience===a)?"":"none");}

function studioStartNew(){studioCurrent=studioBlankProgram();studioAiOutcomes=[];studioStep=1;studioShowTab("builder");studioRenderBuilder();}
function studioEdit(id){const p=studioPrograms.find(x=>x.programId===id);if(!p||p.status==="legacy")return;studioCurrent=JSON.parse(JSON.stringify(p));studioAiOutcomes=[];studioStep=1;studioShowTab("builder");studioRenderBuilder();}
function studioPreview(id){const p=studioPrograms.find(x=>x.programId===id);if(!p)return;studioCurrent=JSON.parse(JSON.stringify(p));studioStep=4;studioShowTab("builder");studioRenderBuilder();}

function studioRenderBuilder(){const el=document.getElementById("studio-builder");if(!el||!studioCurrent)return;studioSyncDuration();el.innerHTML=`<div class="studio-wizard"><aside class="card studio-steps">${[[1,"Basics","sliders"],[2,"Outcomes","bullseye"],[3,"Timeline","calendar3"],[4,"Preview","eye"]].map(([n,l,i])=>`<button class="studio-step-nav ${studioStep===n?"active":""}" onclick="studioGoStep(${n})"><b>${n}</b><span><i class="bi bi-${i}"></i> ${l}</span></button>`).join("")}</aside><main class="card studio-builder-card"><div id="studio-step-content">${studioStepContent()}</div><div class="studio-builder-actions"><button class="secondary" onclick="studioGoStep(${Math.max(1,studioStep-1)})" ${studioStep===1?"disabled":""}><i class="bi bi-arrow-left"></i> Back</button><div style="display:flex;gap:8px"><button class="secondary" onclick="studioSave('draft')"><i class="bi bi-cloud-arrow-down-fill"></i> Save Draft</button>${studioStep<4?`<button onclick="studioGoStep(${studioStep+1})">Continue <i class="bi bi-arrow-right"></i></button>`:`<button onclick="studioPublishAssign()"><i class="bi bi-send-check-fill"></i> Publish & Assign</button>`}</div></div></main></div>`;}

function studioStepContent(){if(studioStep===1)return studioBasics();if(studioStep===2)return studioOutcomes();if(studioStep===3)return studioTimeline();return studioPreviewHtml(studioCurrent);}
function studioBasics(){return `<h2><i class="bi bi-sliders"></i> Program basics</h2><p style="color:var(--muted)">Define who this is for and the shape of the journey.</p><div class="studio-form-grid"><label>Program name<input id="studio-name" value="${escapeAttr(studioCurrent.name)}" oninput="studioCurrent.name=this.value"></label><label>Audience<select onchange="studioCurrent.audience=this.value">${["parent","child","teen","adult","family"].map(v=>`<option ${studioCurrent.audience===v?"selected":""}>${v}</option>`).join("")}</select></label><label class="wide">Description<textarea rows="3" oninput="studioCurrent.description=this.value">${escapeHtml(studioCurrent.description)}</textarea></label><label>Duration (weeks)<input type="number" min="1" max="52" value="${studioCurrent.durationWeeks}" onchange="studioSetDuration(this.value)"></label><label>Sessions per week<input type="number" min="1" max="7" value="${studioCurrent.sessionsPerWeek}" onchange="studioCurrent.sessionsPerWeek=+this.value"></label><label>Theme color<input type="color" value="${escapeAttr(studioCurrent.color)}" onchange="studioCurrent.color=this.value"></label><label>Icon<select onchange="studioCurrent.icon=this.value">${["bi-signpost-split-fill","bi-lightning-charge-fill","bi-heart-pulse-fill","bi-compass-fill","bi-rocket-takeoff-fill","bi-flower1"].map(v=>`<option value="${v}" ${studioCurrent.icon===v?"selected":""}>${v.replace("bi-","").replace(/-/g," ")}</option>`).join("")}</select></label></div><div class="alert" style="margin-top:16px"><i class="bi bi-calculator-fill"></i><span><strong>${studioCurrent.durationWeeks} weeks × ${studioCurrent.sessionsPerWeek} sessions</strong> · planned capacity ${studioCurrent.durationWeeks*studioCurrent.sessionsPerWeek} sessions</span></div>`;}

function studioOutcomes(){const goalOpts=studioGoals.map((g,i)=>`<button class="secondary" style="font-size:11px" onclick="studioAddGoalOutcome(${i})"><i class="bi bi-plus"></i> ${escapeHtml((g.objText||g.objective||"").slice(0,80))}</button>`).join("");const ideas=studioAiOutcomes.map((o,i)=>`<div class="studio-ai-outcome" draggable="true" ondragstart="studioDragOutcome(event,${i})"><span>${escapeHtml(o)}</span><button class="secondary" onclick="studioCopyOutcome(${i})" title="Copy"><i class="bi bi-copy"></i></button><button onclick="studioUseAiOutcome(${i})"><i class="bi bi-plus-lg"></i> Add</button></div>`).join("");return `<h2><i class="bi bi-bullseye"></i> Outcomes & success criteria</h2><p style="color:var(--muted)">Write observable outcomes. Pull from this client's goals or add reusable outcomes.</p>${studioGoals.length?`<div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:15px">${goalOpts}</div>`:""}<div id="studio-outcomes" class="studio-outcome-drop" ondragover="event.preventDefault()" ondrop="studioDropOutcome(event)">${(studioCurrent.outcomes||[]).map((o,i)=>`<div class="studio-outcome"><input value="${escapeAttr(o)}" oninput="studioCurrent.outcomes[${i}]=this.value"><button class="secondary studio-icon-btn" onclick="studioRemoveOutcome(${i})"><i class="bi bi-trash3"></i></button></div>`).join("")||`<small>Drop an AI example here, paste into a new outcome, or add one manually.</small>`}</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:9px"><button class="secondary" onclick="studioAddOutcome('')"><i class="bi bi-plus-lg"></i> Add outcome</button><button class="studio-primary" onclick="studioGenerateOutcomesAi()"><i class="bi bi-stars"></i> Generate clinical-quality examples</button>${studioAiOutcomes.length?`<button class="secondary" onclick="studioUseAllAiOutcomes()"><i class="bi bi-plus-circle"></i> Add all</button>`:""}</div><div id="studio-outcome-ai-status" style="margin-top:9px"></div>${ideas?`<div class="studio-ai-outcomes">${ideas}</div>`:""}<div class="card" style="margin-top:16px;background:var(--surface)"><strong><i class="bi bi-shield-check"></i> Clinical review</strong><p style="font-size:13px;color:var(--muted);margin-bottom:0">Examples are editable drafts. Confirm the baseline, criterion, measurement method, developmental fit, and medical necessity before using them.</p></div>`;}

function studioTimeline(){return `<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><h2><i class="bi bi-calendar3"></i> Journey timeline</h2><p style="color:var(--muted)">Build the sequence. Sessions publish as client activities.</p></div><button class="studio-primary" onclick="studioGenerateAi()"><i class="bi bi-stars"></i> Generate with AI</button></div><div id="studio-weeks">${studioCurrent.weeks.map((w,wi)=>studioWeekHtml(w,wi)).join("")}</div><button class="secondary" onclick="studioAddWeek()"><i class="bi bi-plus-lg"></i> Add week</button><div id="studio-ai-status" style="margin-top:10px"></div>`;}

function studioWeekHtml(w,wi){return `<section class="studio-week"><div class="studio-week-head"><strong>Week ${wi+1}</strong><input value="${escapeAttr(w.phase||"")}" placeholder="Phase or theme" oninput="studioCurrent.weeks[${wi}].phase=this.value"><input value="${escapeAttr(w.milestone||"")}" placeholder="Milestone (optional)" oninput="studioCurrent.weeks[${wi}].milestone=this.value"><button class="secondary studio-icon-btn" onclick="studioMoveWeek(${wi},-1)"><i class="bi bi-arrow-up"></i></button><button class="secondary studio-icon-btn" onclick="studioMoveWeek(${wi},1)"><i class="bi bi-arrow-down"></i></button><button class="secondary studio-icon-btn" onclick="studioRemoveWeek(${wi})"><i class="bi bi-trash3"></i></button></div>${w.sessions.map((s,si)=>studioSessionHtml(s,wi,si)).join("")}<button class="secondary" style="margin:0 10px 10px;font-size:11px" onclick="studioAddSession(${wi})"><i class="bi bi-plus"></i> Add session</button></section>`;}
function studioSessionHtml(s,wi,si){return `<div class="studio-session"><div class="studio-session-top"><span class="studio-chip">${si+1}</span><input value="${escapeAttr(s.title)}" oninput="studioCurrent.weeks[${wi}].sessions[${si}].title=this.value"><select onchange="studioCurrent.weeks[${wi}].sessions[${si}].type=this.value">${["parent-only","child-only","parent+child","graduation"].map(v=>`<option ${s.type===v?"selected":""}>${v}</option>`).join("")}</select><button class="secondary studio-icon-btn" onclick="studioDuplicateSession(${wi},${si})"><i class="bi bi-copy"></i></button><button class="secondary studio-icon-btn" onclick="studioRemoveSession(${wi},${si})"><i class="bi bi-x-lg"></i></button></div><textarea rows="2" placeholder="What happens in this session?" oninput="studioCurrent.weeks[${wi}].sessions[${si}].description=this.value">${escapeHtml(s.description||"")}</textarea><div class="studio-mini-grid"><input value="${escapeAttr(s.focus||"")}" placeholder="Clinical focus" oninput="studioCurrent.weeks[${wi}].sessions[${si}].focus=this.value"><input value="${escapeAttr(s.homework||"")}" placeholder="Between-session practice" oninput="studioCurrent.weeks[${wi}].sessions[${si}].homework=this.value"></div><input style="width:100%;margin-top:8px" value="${escapeAttr((s.activities||[]).join(' | '))}" placeholder="Activities separated by |" oninput="studioCurrent.weeks[${wi}].sessions[${si}].activities=this.value.split('|').map(v=>v.trim()).filter(Boolean)"></div>`;}

function studioPreviewHtml(p){const total=p.weeks.reduce((n,w)=>n+w.sessions.length,0);return `<div class="studio-preview-banner" style="--studio-color:${escapeAttr(p.color)}"><div class="studio-label" style="color:rgba(255,255,255,.78)">${escapeHtml(p.audience.toUpperCase())} · ${p.durationWeeks} WEEKS</div><h1 style="margin:6px 0">${escapeHtml(p.name||"Untitled Program")}</h1><p>${escapeHtml(p.description||"Add a description before publishing.")}</p><div style="display:flex;gap:16px;font-weight:700"><span><i class="bi bi-calendar2-week"></i> ${p.durationWeeks} weeks</span><span><i class="bi bi-collection-play"></i> ${total} sessions</span><span><i class="bi bi-bullseye"></i> ${(p.outcomes||[]).length} outcomes</span></div></div>${(p.outcomes||[]).length?`<div class="card" style="margin-top:14px"><h3>Outcomes</h3>${p.outcomes.map(o=>`<div style="display:flex;gap:8px;margin:7px 0"><i class="bi bi-check-circle-fill" style="color:#2563eb"></i><span>${escapeHtml(o)}</span></div>`).join("")}</div>`:""}<div>${p.weeks.map((w,wi)=>`<div class="studio-preview-week" style="--studio-color:${escapeAttr(p.color)}"><div class="studio-preview-num">${wi+1}</div><div><strong>${escapeHtml(w.phase||("Week "+(wi+1)))}</strong>${w.milestone?`<div class="studio-chip" style="display:inline-block;margin-left:7px">${escapeHtml(w.milestone)}</div>`:""}${w.sessions.map(s=>`<div class="card" style="margin:8px 0;padding:12px"><strong>${escapeHtml(s.title)}</strong><div style="font-size:12px;color:var(--muted)">${escapeHtml(s.description||s.focus||"")}</div></div>`).join("")}</div></div>`).join("")}</div><div class="card" style="margin-top:14px"><label>Assignment start date<input type="date" id="studio-assign-date" value="${new Date().toISOString().slice(0,10)}"></label></div>`;}

function studioCapture(){return studioCurrent;}
function studioGoStep(n){studioCurrent=studioCapture();studioStep=n;studioRenderBuilder();}
function studioSetDuration(v){studioCurrent.durationWeeks=Math.max(1,+v||1);studioSyncDuration();studioRenderBuilder();}
function studioSyncDuration(){if(!studioCurrent)return;while(studioCurrent.weeks.length<studioCurrent.durationWeeks)studioCurrent.weeks.push({week:studioCurrent.weeks.length+1,phase:"Build",milestone:"",sessions:[studioBlankSession(1)]});studioCurrent.weeks=studioCurrent.weeks.slice(0,studioCurrent.durationWeeks);studioCurrent.weeks.forEach((w,i)=>w.week=i+1);}
function studioAddOutcome(v){studioCurrent.outcomes.push(v);studioRenderBuilder();}function studioRemoveOutcome(i){studioCurrent.outcomes.splice(i,1);studioRenderBuilder();}
function studioAddGoalOutcome(i){const g=studioGoals[i]||{};studioAddOutcome(g.objText||g.objective||("Goal "+(i+1)));}
async function studioGenerateOutcomesAi(){setStatus("studio-outcome-ai-status","Generating measurable outcome examples…","loading");try{const res=await apiCall("suggestClinicalOutcomes",{audience:studioCurrent.audience});studioAiOutcomes=res.outcomes||[];studioRenderBuilder();showToast("Generic outcome examples generated. Personalize and clinically review before use.","success");}catch(e){setStatus("studio-outcome-ai-status",e.message,"error");}}
function studioUseAiOutcome(i){const value=studioAiOutcomes[i];if(value&&!studioCurrent.outcomes.includes(value))studioCurrent.outcomes.push(value);studioRenderBuilder();}
function studioUseAllAiOutcomes(){studioAiOutcomes.forEach(v=>{if(v&&!studioCurrent.outcomes.includes(v))studioCurrent.outcomes.push(v);});studioRenderBuilder();}
function studioDragOutcome(event,i){event.dataTransfer.setData("text/plain",studioAiOutcomes[i]||"");event.dataTransfer.effectAllowed="copy";}
function studioDropOutcome(event){event.preventDefault();const value=event.dataTransfer.getData("text/plain").trim();if(value&&!studioCurrent.outcomes.includes(value))studioCurrent.outcomes.push(value);studioRenderBuilder();}
async function studioCopyOutcome(i){const value=studioAiOutcomes[i]||"";try{await navigator.clipboard.writeText(value);showToast("Outcome copied.","success");}catch(_){showToast("Could not copy automatically. Use Add instead.","error");}}
function studioAddWeek(){studioCurrent.weeks.push({week:studioCurrent.weeks.length+1,phase:"Build",milestone:"",sessions:[studioBlankSession(1)]});studioCurrent.durationWeeks=studioCurrent.weeks.length;studioRenderBuilder();}
function studioRemoveWeek(i){if(studioCurrent.weeks.length===1)return;studioCurrent.weeks.splice(i,1);studioCurrent.durationWeeks=studioCurrent.weeks.length;studioRenderBuilder();}
function studioMoveWeek(i,d){const j=i+d;if(j<0||j>=studioCurrent.weeks.length)return;[studioCurrent.weeks[i],studioCurrent.weeks[j]]=[studioCurrent.weeks[j],studioCurrent.weeks[i]];studioRenderBuilder();}
function studioAddSession(wi){studioCurrent.weeks[wi].sessions.push(studioBlankSession(studioCurrent.weeks[wi].sessions.length+1));studioRenderBuilder();}
function studioRemoveSession(wi,si){studioCurrent.weeks[wi].sessions.splice(si,1);studioRenderBuilder();}
function studioDuplicateSession(wi,si){studioCurrent.weeks[wi].sessions.splice(si+1,0,JSON.parse(JSON.stringify(studioCurrent.weeks[wi].sessions[si])));studioRenderBuilder();}

async function studioSave(status){if(!studioCurrent.name.trim()){showToast("Add a program name first.","error");studioStep=1;studioRenderBuilder();return null;}try{const res=await apiCall("saveProgramStudio",{program:studioCurrent,status});studioCurrent=res.program;const i=studioPrograms.findIndex(p=>p.programId===studioCurrent.programId);if(i>=0)studioPrograms[i]=studioCurrent;else studioPrograms.unshift(studioCurrent);showToast(status==="draft"?"Draft saved.":"Program published.","success");studioRenderLibrary();return studioCurrent;}catch(e){showToast(e.message,"error");return null;}}
async function studioPublishAssign(){const saved=await studioSave("published");if(!saved)return;const startDate=document.getElementById("studio-assign-date")?.value||new Date().toISOString().slice(0,10);try{await apiCall("assignProgramStudio",{programId:saved.programId,startDate});showToast("Program published and assigned.","success");const root=document.getElementById("section-program-admin");setTimeout(()=>initProgramAdminSection(root),700);}catch(e){showToast("Saved, but assignment failed: "+e.message,"error");}}
async function studioDuplicate(id){try{const res=await apiCall("duplicateProgramStudio",{programId:id});studioPrograms.unshift(res.program);studioRenderLibrary();showToast("Draft copy created.","success");}catch(e){showToast(e.message,"error");}}
async function studioArchive(id){if(!confirm("Archive this program? Existing client assignments will continue to work."))return;try{await apiCall("archiveProgramStudio",{programId:id});studioPrograms=studioPrograms.filter(p=>p.programId!==id);studioRenderLibrary();showToast("Program archived.","success");}catch(e){showToast(e.message,"error");}}
async function studioAssignExisting(id){const date=prompt("Start date (YYYY-MM-DD)",new Date().toISOString().slice(0,10));if(!date)return;try{const p=studioPrograms.find(x=>x.programId===id);if(p?.status==="legacy")await apiCall("assignProgram",{programId:id,startDate:date});else await apiCall("assignProgramStudio",{programId:id,startDate:date});showToast("Program assigned.","success");initProgramAdminSection(document.getElementById("section-program-admin"));}catch(e){showToast(e.message,"error");}}

async function studioGenerateAi(){const count=Math.max(1,studioCurrent.durationWeeks*studioCurrent.sessionsPerWeek);setStatus("studio-ai-status","Generating a generic outline…","loading");try{const res=await apiCall("suggestSessionTopics",{numSessions:Math.min(count,24),audience:studioCurrent.audience});const suggestions=res.suggestions||[];const weeks=[];for(let i=0;i<suggestions.length;i+=studioCurrent.sessionsPerWeek){weeks.push({week:weeks.length+1,phase:weeks.length===0?"Foundation":weeks.length===Math.ceil(suggestions.length/studioCurrent.sessionsPerWeek)-1?"Generalize":"Build",milestone:"",sessions:suggestions.slice(i,i+studioCurrent.sessionsPerWeek).map(s=>({title:s.title||"Session",description:s.rationale||"",focus:s.focus||"",homework:s.homework||"",type:"parent+child",activities:s.suggestedActivities||[]}))});}if(weeks.length){studioCurrent.weeks=weeks;studioCurrent.durationWeeks=weeks.length;}studioRenderBuilder();showToast("Generic AI outline generated. Personalize and review every session before publishing.","success");}catch(e){setStatus("studio-ai-status",e.message,"error");}}
